java_test(
    name = "tests",
    test_class = "org.picocontainer.tests.integration.MyTests",
    srcs = ["MyTests.java"],
    deps =[
      "//src/java/com/intellij/util/pico:PicoContainer",
        "//src/java/com/intellij/util:intellij_util",
        "//src/java/org/jetbrains/annotations:jetbrains_annotations",
        "//src/java/org/picocontainer:pico_base",
        "//src/java/org/picocontainer/defaults:pico_defaults",
     ]
)