java_library(
    name = "PicoContainer",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/java/com/intellij/util:intellij_util",
        "//src/java/org/jetbrains/annotations:jetbrains_annotations",
        "//src/java/org/picocontainer:pico_base",
        "//src/java/org/picocontainer/defaults:pico_defaults",
    ]
)