java_library(
    name = "pico_defaults",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/java/org/jetbrains/annotations:jetbrains_annotations",
        "//src/java/org/picocontainer:pico_base",
    ],
)