java_library(
    name = "intellij_util",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/java/org/jetbrains/annotations:jetbrains_annotations",
    ],
)